version: '3.8'

services:

  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ivan
      MYSQL_TCP_PORT: 3306
    volumes:
      - "./sql-scripts:/docker-entrypoint-initdb.d"
    ports:
      - "3308:3306"

  backend:
    container_name: backend
    depends_on:
      - db
    build: .
    image: backend
    environment:
      DB_SERVER: db
      DATA_HOST_PORT: db:3306
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ivan
    ports:
      - "8081:8080"









